### ISSUE TITLE
POM file for SDK

### ISSUE THREAD

**Issue by bmoryan** [silanis/esl.sdk.java#4]

**Comment by bmoryan** [comment]
Maybe I missed it, but it would be nice if there is a pom file for the SDK. The SDK is a zip file with some jar files, and a maven dependency entry. The problem is even if you then manually install the artefact into maven (plus sources (thank you for that) and docs), with no pom file maven can't manage the sdk's dependencies.

What I did has clone the dev branch, checkout the v10.10.1 tag and then mvn clean install it myself. Not insurmountable, but then I didn't need the SDK zip file at all. Might be easier to distribute the SDK with a pom file (in addition to the jars), plus instructions on how to install it locally.

Even better for developer use would be to either add it to the maven central repo or host your own maven repo, but that's a lot of work.

**Comment by ehardy** [comment]
Hi,

The SDK is available in the Central Maven repo. Please have a look at:

http://docs.e-signlive.com/doku.php?id=esl:e-signlive_getting_started

Regards,

Etienne

**Comment by bmoryan** [comment]
Thanks!
